spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?allowMultiQueries=true
  redis:
    host: localhost
    port: 6379


